### PR TITLE
Partner Page ,Footer ,Categories and Coming Soon Page Updated 

### PR DESCRIPTION
**Pull request by Abhishek971999**
1) Partner Page has been updated 
Capture

2) Footer Component has been updated
Capture

### CODE REVIEW

**Comment by kumarsandeep91** [comment]
@Abhishek971999 We also dont support live tracking. can you remove that or change it to `Live Updates`

**Comment by Abhishek971999** [comment]
Added more categories to Page
Capture
Capture
Capture

**Comment by Abhishek971999** [comment]
Updated the Coming soon page along with the links mentioned in the footer
Capture

**Comment by kumarsandeep91** [comment]
Awesome work :+1:

**Pull request merged**
